name: CI
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./cosmos.json
          parameters: location=NorthEurope primaryRegion=WestEurope secondaryRegion=EastUS databaseName=cosmosdb-nuranc-github containername=cont-nuranc-github
